server:
  port: 8088
logging:
  level:
    com.multiple.data.source.service.*: DEBUG

spring:
  application:
    name: multi-redis-source
  redis:
    password: root
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 100
        max-wait:  -1
        max-idle:  10
        min-idle:  0
    datasource:
      db1:
        database: 2

knife4j:
  # 是否开启加强模式 true开启  false关闭
  enable: true
  setting:
    # 是否开启调试功能  true开启  false关闭
    enableDebug: true
  basic:
    # 是否开启认证功能  true开启  false关闭
    enable: false
    username: test
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/**.xml

stone:
  redis:
   # 开启动态切换redis db 可选,默认不开启
    dynamic-database: true